/**
 * Brand catalog for Style preferences — mirrors the backend scraper's
 * BRAND_CATALOG (supabase/functions/feed-scrape/catalog.ts in the web repo).
 * Names must match `feed_products.brand` EXACTLY: the feed's brand filter and
 * feed-page's `.in("brand", prefs.stores)` both compare against these strings.
 * If the backend catalog gains a brand, add it here too.
 */

export interface BrandGroup {
  title: string;
  brands: string[];
}

export const BRAND_GROUPS: BrandGroup[] = [
  {
    title: 'BUDGET-FRIENDLY',
    brands: [
      'H&M',
      'Shein',
      'Fashion Nova',
      'Forever 21',
      'Boohoo',
      'PrettyLittleThing',
      'Missguided',
      'Nasty Gal',
      'Old Navy',
      'Target',
      'Cider',
      'YesStyle',
      'Uniqlo',
      'Bershka',
      'Stradivarius',
      'Pull&Bear',
      'Edikted',
      'Hot Topic',
      'Garage',
    ],
  },
  {
    title: 'MID-RANGE',
    brands: [
      'Zara',
      'Mango',
      'Abercrombie & Fitch',
      'Aerie',
      'American Eagle',
      'Hollister',
      'Gap',
      'Banana Republic',
      'J.Crew',
      "Levi's",
      'Madewell',
      'Dynamite',
      'Brandy Melville',
      'PacSun',
      'Urban Outfitters',
      'Princess Polly',
      'White Fox',
      'Oh Polly',
      'Meshki',
      'Beginning Boutique',
      'Tiger Mist',
      'Motel Rocks',
      'I.AM.GIA',
      'Jaded London',
      'Pretty Lavish',
      'Dolls Kill',
      'Killstar',
      'Tripp NYC',
      'Disturbia',
      'BlackCraft Cult',
      'RebelsMarket',
      'The Ragged Priest',
      'Punk Rave',
      'Sourpuss Clothing',
      'Gymshark',
      'Nike',
      'Adidas',
      'New Balance',
      'Fabletics',
      'Outdoor Voices',
      'Set Active',
      'Columbia',
      'Ann Taylor',
      'LOFT',
      'J.Jill',
      'Talbots',
      "Chico's",
      'White House Black Market',
      'Carhartt WIP',
      'Stüssy',
      'The Hundreds',
      'Anti Social Social Club',
      'Unif',
      'Free Label',
      'ASOS',
      'Everlane',
      'COS',
      '& Other Stories',
      'Massimo Dutti',
    ],
  },
  {
    title: 'PREMIUM',
    brands: [
      'Aritzia',
      'Reformation',
      'Free People',
      'Free People Movement',
      'Anthropologie',
      'Revolve',
      'Nordstrom',
      'House of CB',
      'Skims',
      'Lululemon',
      'Alo Yoga',
      'Vuori',
      'Patagonia',
      'The North Face',
      'AllSaints',
      'Club Monaco',
      'Theory',
      'Vince',
      'Sandro',
      'Maje',
      'Rag & Bone',
      'Kate Spade',
      'Tory Burch',
      'Ted Baker',
      'Reiss',
      'Supreme',
      'Kith',
      'Palace',
      'BAPE',
      'Fear of God',
      'Essentials',
    ],
  },
  {
    title: 'LUXURY',
    brands: [
      'Chanel',
      'Dior',
      'Prada',
      'Gucci',
      'Louis Vuitton',
      'Saint Laurent',
      'Balenciaga',
      'Versace',
      'Fendi',
      'Givenchy',
      'Valentino',
      'Bottega Veneta',
      'Celine',
      'Roberto Cavalli',
      'Pucci',
      'Alexander McQueen',
      'Tom Ford',
      'Miu Miu',
      'Loewe',
      'Off-White',
      'Maison Margiela',
      'Vivienne Westwood',
      'Rick Owens',
      'Balmain',
      'Acne Studios',
      'Jacquemus',
      'SSENSE',
      'Moncler',
      'Canada Goose',
      'Mackage',
      'Moose Knuckles',
    ],
  },
];
