// Brand catalog for the monthly feed scraper.
//
// One entry per brand the feed scrapes. `tier` buckets the brand into the
// same BUDGETS options the app's preferences screen offers ('Budget' |
// 'Mid-range' | 'Premium' | 'Luxury'), and `styles` uses the app's STYLES
// vocabulary (Classic, Minimal, Trendy, Streetwear, Romantic, Edgy, Preppy,
// Boho) so scraped rows join cleanly against user preferences.
//
// `name` strings are what get written to feed_scraped_products.brand and must
// stay in sync with src/lib/brands.ts::STORES entries where they overlap —
// the app matches user-saved stores against these verbatim (after
// normalization). Never rename an existing entry; add new ones instead.

export type BudgetTier = 'Budget' | 'Mid-range' | 'Premium' | 'Luxury';

export interface CatalogBrand {
  name: string;
  domain: string;
  tier: BudgetTier;
  styles: string[];
}

export const BRAND_CATALOG: CatalogBrand[] = [
  // ---- Fast fashion / budget ----
  { name: 'H&M', domain: 'hm.com', tier: 'Budget', styles: ['Trendy', 'Minimal'] },
  { name: 'Shein', domain: 'shein.com', tier: 'Budget', styles: ['Trendy'] },
  { name: 'Fashion Nova', domain: 'fashionnova.com', tier: 'Budget', styles: ['Trendy', 'Edgy'] },
  { name: 'Forever 21', domain: 'forever21.com', tier: 'Budget', styles: ['Trendy'] },
  { name: 'Boohoo', domain: 'boohoo.com', tier: 'Budget', styles: ['Trendy'] },
  { name: 'PrettyLittleThing', domain: 'prettylittlething.com', tier: 'Budget', styles: ['Trendy'] },
  { name: 'Missguided', domain: 'missguided.com', tier: 'Budget', styles: ['Trendy'] },
  { name: 'Nasty Gal', domain: 'nastygal.com', tier: 'Budget', styles: ['Trendy', 'Edgy'] },
  { name: 'Old Navy', domain: 'oldnavy.com', tier: 'Budget', styles: ['Classic', 'Preppy'] },
  { name: 'Target', domain: 'target.com', tier: 'Budget', styles: ['Classic', 'Trendy'] },
  { name: 'Cider', domain: 'shopcider.com', tier: 'Budget', styles: ['Trendy'] },
  { name: 'YesStyle', domain: 'yesstyle.com', tier: 'Budget', styles: ['Trendy', 'Minimal'] },
  { name: 'Uniqlo', domain: 'uniqlo.com', tier: 'Budget', styles: ['Minimal', 'Classic'] },
  { name: 'Bershka', domain: 'bershka.com', tier: 'Budget', styles: ['Trendy', 'Streetwear'] },
  { name: 'Stradivarius', domain: 'stradivarius.com', tier: 'Budget', styles: ['Trendy'] },
  { name: 'Pull&Bear', domain: 'pullandbear.com', tier: 'Budget', styles: ['Trendy', 'Streetwear'] },
  { name: 'Edikted', domain: 'edikted.com', tier: 'Budget', styles: ['Trendy'] },
  { name: 'Hot Topic', domain: 'hottopic.com', tier: 'Budget', styles: ['Edgy'] },
  { name: 'Garage', domain: 'garageclothing.com', tier: 'Budget', styles: ['Trendy'] },

  // ---- Mid-range ----
  { name: 'Zara', domain: 'zara.com', tier: 'Mid-range', styles: ['Trendy', 'Minimal', 'Classic'] },
  { name: 'Mango', domain: 'shop.mango.com', tier: 'Mid-range', styles: ['Classic', 'Minimal'] },
  { name: 'Abercrombie & Fitch', domain: 'abercrombie.com', tier: 'Mid-range', styles: ['Classic', 'Preppy'] },
  { name: 'Aerie', domain: 'aerie.com', tier: 'Mid-range', styles: ['Romantic', 'Minimal'] },
  { name: 'American Eagle', domain: 'ae.com', tier: 'Mid-range', styles: ['Classic', 'Preppy'] },
  { name: 'Hollister', domain: 'hollisterco.com', tier: 'Mid-range', styles: ['Preppy', 'Classic'] },
  { name: 'Gap', domain: 'gap.com', tier: 'Mid-range', styles: ['Classic', 'Minimal'] },
  { name: 'Banana Republic', domain: 'bananarepublic.com', tier: 'Mid-range', styles: ['Classic'] },
  { name: 'J.Crew', domain: 'jcrew.com', tier: 'Mid-range', styles: ['Preppy', 'Classic'] },
  { name: "Levi's", domain: 'levi.com', tier: 'Mid-range', styles: ['Classic', 'Streetwear'] },
  { name: 'Madewell', domain: 'madewell.com', tier: 'Mid-range', styles: ['Classic', 'Minimal'] },
  { name: 'Dynamite', domain: 'dynamiteclothing.com', tier: 'Mid-range', styles: ['Trendy', 'Classic'] },
  { name: 'Brandy Melville', domain: 'brandymelville.com', tier: 'Mid-range', styles: ['Minimal', 'Trendy'] },
  { name: 'PacSun', domain: 'pacsun.com', tier: 'Mid-range', styles: ['Streetwear', 'Trendy'] },
  { name: 'Urban Outfitters', domain: 'urbanoutfitters.com', tier: 'Mid-range', styles: ['Trendy', 'Boho', 'Edgy'] },
  { name: 'Princess Polly', domain: 'princesspolly.com', tier: 'Mid-range', styles: ['Trendy'] },
  { name: 'White Fox', domain: 'whitefoxboutique.com', tier: 'Mid-range', styles: ['Trendy'] },
  { name: 'Oh Polly', domain: 'ohpolly.com', tier: 'Mid-range', styles: ['Trendy', 'Romantic'] },
  { name: 'Meshki', domain: 'meshki.com', tier: 'Mid-range', styles: ['Trendy', 'Minimal'] },
  { name: 'Beginning Boutique', domain: 'beginningboutique.com', tier: 'Mid-range', styles: ['Trendy', 'Romantic'] },
  { name: 'Tiger Mist', domain: 'tigermist.com', tier: 'Mid-range', styles: ['Trendy'] },
  { name: 'Motel Rocks', domain: 'motelrocks.com', tier: 'Mid-range', styles: ['Trendy', 'Edgy'] },
  { name: 'I.AM.GIA', domain: 'iamgia.com', tier: 'Mid-range', styles: ['Edgy', 'Streetwear'] },
  { name: 'Jaded London', domain: 'jadedldn.com', tier: 'Mid-range', styles: ['Streetwear', 'Edgy'] },
  { name: 'Pretty Lavish', domain: 'prettylavish.co.uk', tier: 'Mid-range', styles: ['Romantic', 'Classic'] },
  { name: 'Dolls Kill', domain: 'dollskill.com', tier: 'Mid-range', styles: ['Edgy'] },
  { name: 'Killstar', domain: 'killstar.com', tier: 'Mid-range', styles: ['Edgy'] },
  { name: 'Tripp NYC', domain: 'trippnyc.com', tier: 'Mid-range', styles: ['Edgy'] },
  { name: 'Disturbia', domain: 'disturbia.co.uk', tier: 'Mid-range', styles: ['Edgy'] },
  { name: 'BlackCraft Cult', domain: 'blackcraftcult.com', tier: 'Mid-range', styles: ['Edgy'] },
  { name: 'RebelsMarket', domain: 'rebelsmarket.com', tier: 'Mid-range', styles: ['Edgy'] },
  { name: 'The Ragged Priest', domain: 'theraggedpriest.com', tier: 'Mid-range', styles: ['Edgy', 'Streetwear'] },
  { name: 'Punk Rave', domain: 'punkrave.ch', tier: 'Mid-range', styles: ['Edgy'] },
  { name: 'Sourpuss Clothing', domain: 'sourpussclothing.com', tier: 'Mid-range', styles: ['Edgy'] },
  { name: 'Gymshark', domain: 'gymshark.com', tier: 'Mid-range', styles: ['Streetwear', 'Minimal'] },
  { name: 'Nike', domain: 'nike.com', tier: 'Mid-range', styles: ['Streetwear'] },
  { name: 'Adidas', domain: 'adidas.com', tier: 'Mid-range', styles: ['Streetwear'] },
  { name: 'New Balance', domain: 'newbalance.com', tier: 'Mid-range', styles: ['Streetwear', 'Classic'] },
  { name: 'Fabletics', domain: 'fabletics.com', tier: 'Mid-range', styles: ['Streetwear', 'Minimal'] },
  { name: 'Outdoor Voices', domain: 'outdoorvoices.com', tier: 'Mid-range', styles: ['Minimal'] },
  { name: 'Set Active', domain: 'setactive.co', tier: 'Mid-range', styles: ['Minimal', 'Trendy'] },
  { name: 'Columbia', domain: 'columbia.com', tier: 'Mid-range', styles: ['Classic'] },
  { name: 'Ann Taylor', domain: 'anntaylor.com', tier: 'Mid-range', styles: ['Classic'] },
  { name: 'LOFT', domain: 'loft.com', tier: 'Mid-range', styles: ['Classic'] },
  { name: 'J.Jill', domain: 'jjill.com', tier: 'Mid-range', styles: ['Classic'] },
  { name: 'Talbots', domain: 'talbots.com', tier: 'Mid-range', styles: ['Classic'] },
  { name: "Chico's", domain: 'chicos.com', tier: 'Mid-range', styles: ['Classic'] },
  { name: 'White House Black Market', domain: 'whitehouseblackmarket.com', tier: 'Mid-range', styles: ['Classic'] },
  { name: 'Carhartt WIP', domain: 'carhartt-wip.com', tier: 'Mid-range', styles: ['Streetwear'] },
  { name: 'Stüssy', domain: 'stussy.com', tier: 'Mid-range', styles: ['Streetwear'] },
  { name: 'The Hundreds', domain: 'thehundreds.com', tier: 'Mid-range', styles: ['Streetwear'] },
  { name: 'Anti Social Social Club', domain: 'antisocialsocialclub.com', tier: 'Mid-range', styles: ['Streetwear'] },
  { name: 'Unif', domain: 'unifclothing.com', tier: 'Mid-range', styles: ['Edgy', 'Trendy'] },
  { name: 'Free Label', domain: 'freelabel.com', tier: 'Mid-range', styles: ['Minimal'] },
  { name: 'ASOS', domain: 'asos.com', tier: 'Mid-range', styles: ['Trendy'] },
  { name: 'Everlane', domain: 'everlane.com', tier: 'Mid-range', styles: ['Minimal', 'Classic'] },
  { name: 'COS', domain: 'cos.com', tier: 'Mid-range', styles: ['Minimal'] },
  { name: '& Other Stories', domain: 'stories.com', tier: 'Mid-range', styles: ['Romantic', 'Classic'] },
  { name: 'Massimo Dutti', domain: 'massimodutti.com', tier: 'Mid-range', styles: ['Classic', 'Minimal'] },

  // ---- Premium / contemporary ----
  { name: 'Aritzia', domain: 'aritzia.com', tier: 'Premium', styles: ['Minimal', 'Classic', 'Trendy'] },
  { name: 'Reformation', domain: 'thereformation.com', tier: 'Premium', styles: ['Romantic', 'Classic'] },
  { name: 'Free People', domain: 'freepeople.com', tier: 'Premium', styles: ['Boho', 'Romantic'] },
  { name: 'Free People Movement', domain: 'freepeoplemovement.com', tier: 'Premium', styles: ['Boho', 'Minimal'] },
  { name: 'Anthropologie', domain: 'anthropologie.com', tier: 'Premium', styles: ['Boho', 'Romantic'] },
  { name: 'Revolve', domain: 'revolve.com', tier: 'Premium', styles: ['Trendy', 'Romantic'] },
  { name: 'Nordstrom', domain: 'nordstrom.com', tier: 'Premium', styles: ['Classic', 'Trendy'] },
  { name: 'House of CB', domain: 'houseofcb.com', tier: 'Premium', styles: ['Romantic', 'Trendy'] },
  { name: 'Skims', domain: 'skims.com', tier: 'Premium', styles: ['Minimal'] },
  { name: 'Lululemon', domain: 'lululemon.com', tier: 'Premium', styles: ['Minimal', 'Streetwear'] },
  { name: 'Alo Yoga', domain: 'aloyoga.com', tier: 'Premium', styles: ['Minimal', 'Streetwear'] },
  { name: 'Vuori', domain: 'vuoriclothing.com', tier: 'Premium', styles: ['Minimal'] },
  { name: 'Patagonia', domain: 'patagonia.com', tier: 'Premium', styles: ['Classic'] },
  { name: 'The North Face', domain: 'thenorthface.com', tier: 'Premium', styles: ['Streetwear', 'Classic'] },
  { name: 'AllSaints', domain: 'allsaints.com', tier: 'Premium', styles: ['Edgy', 'Minimal'] },
  { name: 'Club Monaco', domain: 'clubmonaco.com', tier: 'Premium', styles: ['Classic', 'Minimal'] },
  { name: 'Theory', domain: 'theory.com', tier: 'Premium', styles: ['Classic', 'Minimal'] },
  { name: 'Vince', domain: 'vince.com', tier: 'Premium', styles: ['Minimal', 'Classic'] },
  { name: 'Sandro', domain: 'us.sandro-paris.com', tier: 'Premium', styles: ['Classic', 'Trendy'] },
  { name: 'Maje', domain: 'us.maje.com', tier: 'Premium', styles: ['Romantic', 'Trendy'] },
  { name: 'Rag & Bone', domain: 'rag-bone.com', tier: 'Premium', styles: ['Minimal', 'Edgy'] },
  { name: 'Kate Spade', domain: 'katespade.com', tier: 'Premium', styles: ['Preppy', 'Romantic'] },
  { name: 'Tory Burch', domain: 'toryburch.com', tier: 'Premium', styles: ['Preppy', 'Classic'] },
  { name: 'Ted Baker', domain: 'tedbaker.com', tier: 'Premium', styles: ['Classic', 'Romantic'] },
  { name: 'Reiss', domain: 'reiss.com', tier: 'Premium', styles: ['Classic', 'Minimal'] },
  { name: 'Supreme', domain: 'supremenewyork.com', tier: 'Premium', styles: ['Streetwear'] },
  { name: 'Kith', domain: 'kith.com', tier: 'Premium', styles: ['Streetwear'] },
  { name: 'Palace', domain: 'palaceskateboards.com', tier: 'Premium', styles: ['Streetwear'] },
  { name: 'BAPE', domain: 'bape.com', tier: 'Premium', styles: ['Streetwear'] },
  { name: 'Fear of God', domain: 'fearofgod.com', tier: 'Premium', styles: ['Streetwear', 'Minimal'] },
  { name: 'Essentials', domain: 'fearofgod.com', tier: 'Premium', styles: ['Streetwear', 'Minimal'] },

  // ---- Luxury ----
  { name: 'Chanel', domain: 'chanel.com', tier: 'Luxury', styles: ['Classic', 'Romantic'] },
  { name: 'Dior', domain: 'dior.com', tier: 'Luxury', styles: ['Classic', 'Romantic'] },
  { name: 'Prada', domain: 'prada.com', tier: 'Luxury', styles: ['Classic', 'Minimal'] },
  { name: 'Gucci', domain: 'gucci.com', tier: 'Luxury', styles: ['Trendy', 'Edgy'] },
  { name: 'Louis Vuitton', domain: 'louisvuitton.com', tier: 'Luxury', styles: ['Classic'] },
  { name: 'Saint Laurent', domain: 'ysl.com', tier: 'Luxury', styles: ['Edgy', 'Classic'] },
  { name: 'Balenciaga', domain: 'balenciaga.com', tier: 'Luxury', styles: ['Streetwear', 'Edgy'] },
  { name: 'Versace', domain: 'versace.com', tier: 'Luxury', styles: ['Edgy', 'Romantic'] },
  { name: 'Fendi', domain: 'fendi.com', tier: 'Luxury', styles: ['Classic'] },
  { name: 'Givenchy', domain: 'givenchy.com', tier: 'Luxury', styles: ['Classic', 'Edgy'] },
  { name: 'Valentino', domain: 'valentino.com', tier: 'Luxury', styles: ['Romantic', 'Classic'] },
  { name: 'Bottega Veneta', domain: 'bottegaveneta.com', tier: 'Luxury', styles: ['Minimal', 'Classic'] },
  { name: 'Celine', domain: 'celine.com', tier: 'Luxury', styles: ['Minimal', 'Classic'] },
  { name: 'Roberto Cavalli', domain: 'robertocavalli.com', tier: 'Luxury', styles: ['Romantic', 'Edgy'] },
  { name: 'Pucci', domain: 'pucci.com', tier: 'Luxury', styles: ['Trendy', 'Romantic'] },
  { name: 'Alexander McQueen', domain: 'alexandermcqueen.com', tier: 'Luxury', styles: ['Edgy'] },
  { name: 'Tom Ford', domain: 'tomford.com', tier: 'Luxury', styles: ['Classic'] },
  { name: 'Miu Miu', domain: 'miumiu.com', tier: 'Luxury', styles: ['Romantic', 'Trendy'] },
  { name: 'Loewe', domain: 'loewe.com', tier: 'Luxury', styles: ['Minimal', 'Trendy'] },
  { name: 'Off-White', domain: 'off---white.com', tier: 'Luxury', styles: ['Streetwear'] },
  { name: 'Maison Margiela', domain: 'maisonmargiela.com', tier: 'Luxury', styles: ['Minimal', 'Edgy'] },
  { name: 'Vivienne Westwood', domain: 'viviennewestwood.com', tier: 'Luxury', styles: ['Edgy', 'Romantic'] },
  { name: 'Rick Owens', domain: 'rickowens.eu', tier: 'Luxury', styles: ['Edgy'] },
  { name: 'Balmain', domain: 'balmain.com', tier: 'Luxury', styles: ['Edgy', 'Classic'] },
  { name: 'Acne Studios', domain: 'acnestudios.com', tier: 'Luxury', styles: ['Minimal', 'Edgy'] },
  { name: 'Jacquemus', domain: 'jacquemus.com', tier: 'Luxury', styles: ['Minimal', 'Romantic'] },
  { name: 'SSENSE', domain: 'ssense.com', tier: 'Luxury', styles: ['Minimal', 'Edgy', 'Streetwear'] },
  { name: 'Moncler', domain: 'moncler.com', tier: 'Luxury', styles: ['Classic'] },
  { name: 'Canada Goose', domain: 'canadagoose.com', tier: 'Luxury', styles: ['Classic'] },
  { name: 'Mackage', domain: 'mackage.com', tier: 'Luxury', styles: ['Classic', 'Minimal'] },
  { name: 'Moose Knuckles', domain: 'mooseknucklescanada.com', tier: 'Luxury', styles: ['Classic', 'Edgy'] },
];
